# Site settings
title: Run Lift Code
email: noofyourbusiness
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.runliftcode.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

include: [".htaccess", "_assets"]

sass:
    load_paths:
        - _sass
        - /opt/build/cache/bundle/ruby/2.7.0/gems/bootstrap-5.1.3/assets/stylesheets

future: true
# timezone: America/Chicago